In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

%load_ext autoreload
%autoreload 2

In [ ]:
import numpy as np 

t_matrix = np.eye(4)
t_matrix[0, 3] = 2

rt = np.random.randint(0,9,(4,4))

t_matrix

rt[3,:-1] = 0
rt[3,-1] = 1

rt

rt @ t_matrix
np.linalg.inv(np.linalg.inv(t_matrix) @ np.linalg.inv(rt))

In [ ]:
cam2world_matrix =  np.random.randint(0,9,(4,4))
cam2world_matrix[3,:-1] = 0
cam2world_matrix[3,-1] = 1

t_vec = np.array([2,0,0])
t_matrix = np.eye(4)
t_matrix[:3,3] = t_vec



c2l = cam2world_matrix @ t_matrix
light_location = c2l[:3,3]

cam2world_matrix
t_matrix
c2l
light_location

In [ ]:
from pathlib import Path

BASE_PATH = Path('~/dev').expanduser()
DATASET_PATH = BASE_PATH/'data'/'dataset'
SCENE_PATH =  BASE_PATH/'data'/'scenes'
CONFIG_FOLDER = BASE_PATH/'data'/'dataset'/'config'


BASE_PATH
CONFIG_FOLDER

In [ ]:
import json
data = {1 : 'ciao'}
with open('data.json', 'w') as f:
    json.dump(data, f)

In [ ]:
import numpy as np
def n_points_on_circle(r, center, num_points):
    theta = np.linspace(0,2*np.pi,num_points,endpoint=False); 
    x = r * np.cos(theta)+center[0]
    y = r * np.sin(theta)+center[1]
    z = np.broadcast_to(center[2],num_points)

    print(x)
    print(y)
    print(z)

    xyz = np.stack((x,y,z),axis=-1)
    return xyz


n_points_on_circle(0.6,[0,0,0],10)

In [ ]:
import shutil

shutil.move('/home/eyecan/Downloads/prova/render/','/home/eyecan/dev/data/blender/light360_2')

In [ ]:
import shutil 
shutil.rmtree('/home/eyecan/dev/data/blender_tmp/truck_HD')

In [ ]:
import shutil
from pathlib import Path 
p = Path('/home/eyecan/dev/data/blender_tmp/truck_HD_light_360/bbox.npy')
shutil.copy(p,'/home/eyecan/dev/data/blender_tmp/prova_copy')

In [ ]:
BASE_PATH = Path('~/dev').expanduser()      #TOCHANGE cosi è specifico per questo pc 
DATASET_PATH = BASE_PATH/'data'/'dataset'
BLENDER_PATH = BASE_PATH/'data'/'blender_tmp'

in_blender_tmp_folder = BLENDER_PATH / id
out_underfolder_path = DATASET_PATH / 'train' / id
render_path = in_blender_tmp_folder / 'render'

shutil.move(str(render_path), str(out_underfolder_path))   #DEBUG 
shutil.rmtree(in_blender_tmp_folder) #DEBUG 

In [ ]:
import numpy as np 

n= 50
a = np.arange(0,n)
b = a.copy()
np.random.shuffle(b)




In [ ]:
a = np.random.randint(0,9,(10,4))
a
np.random.shuffle(a)
a

In [ ]:
#FOR GENERATING UNIQUE IDS 

import itertools
import string
import os 
import yaml


BASE_PATH = Path('~/dev').expanduser()      #TOCHANGE cosi è specifico per questo pc 
DATASET_PATH = BASE_PATH/'data'/'dataset'

valid_chars = set(string.ascii_lowercase + string.digits)

unique_id_generator = itertools.combinations(valid_chars, 5)

id_file = os.path.join(DATASET_PATH,'id.yml')

with open(id_file,"r") as f :
    id_dict = yaml.load(f, Loader=yaml.FullLoader)

print(id_dict)

for gen_id in unique_id_generator:
    _id = "".join(gen_id)
    if _id not in id_dict :
        id = _id

print(id)



In [ ]:
import numpy as np 

tv_list = [[2,0,0],[0,0,2],[-2,0,0],[0,0,-2]]
t_vecs = np.array(tv_list)   #convert the t_vector in numpy array  
t_matrices = np.zeros((t_vecs.shape[0],4,4))

#generate translation matrices from translation vector list
for i, t_vec in enumerate(t_vecs) :
    t_matrices[i] = np.eye(4)                                        
    t_matrices[i,:3,3] = t_vec

t_matrices


In [ ]:
import numpy as np 
c_idxs = np.arange(0,20)
l_idxs = c_idxs.copy()
c_idxs
l_idxs

np.random.shuffle(c_idxs)  
np.random.shuffle(l_idxs)

print([(c_id,l_id) for c_id, l_id in zip(c_idxs,l_idxs)])
   

In [65]:
import numpy as np 
import math 

smaller_dome_radius = 2.0
perc_error_dome = 0.05
num_poses = 50
num_repeated_lights = 4

unique_lights = math.ceil(num_poses / num_repeated_lights)

errors = np.round(perc_error_dome * smaller_dome_radius * np.random.uniform(-1.0,1.0,unique_lights),4)

c_idxs = np.arange(0,num_poses)
l_idxs = np.arange(0,unique_lights)
l_idxs = np.repeat(l_idxs,num_repeated_lights)[:num_poses]

np.random.shuffle(c_idxs)  
np.random.shuffle(l_idxs)

errors
l_idxs
errors[l_idxs]
len(np.unique(errors[l_idxs]))
unique_lights

array([ 0.016 , -0.0226, -0.0472, -0.0347,  0.0814, -0.0984,  0.0358,
       -0.0863, -0.0613,  0.0528, -0.0009,  0.0579,  0.016 ])

array([ 3,  0,  4,  8, 10,  6,  4, 10,  3,  3, 12,  5,  9,  3,  4,  9,  6,
        8,  2, 12,  0,  7,  5, 11, 11,  2,  1,  5,  9,  7,  6,  1, 11,  9,
       11,  8,  7,  0,  7,  8,  4,  1,  2,  1,  2, 10,  6, 10,  0,  5])

array([-0.0347,  0.016 ,  0.0814, -0.0613, -0.0009,  0.0358,  0.0814,
       -0.0009, -0.0347, -0.0347,  0.016 , -0.0984,  0.0528, -0.0347,
        0.0814,  0.0528,  0.0358, -0.0613, -0.0472,  0.016 ,  0.016 ,
       -0.0863, -0.0984,  0.0579,  0.0579, -0.0472, -0.0226, -0.0984,
        0.0528, -0.0863,  0.0358, -0.0226,  0.0579,  0.0528,  0.0579,
       -0.0613, -0.0863,  0.016 , -0.0863, -0.0613,  0.0814, -0.0226,
       -0.0472, -0.0226, -0.0472, -0.0009,  0.0358, -0.0009,  0.016 ,
       -0.0984])

12

13

In [44]:
l_idxs

array([ 3,  3,  4,  0,  5,  6, 12,  0,  3,  8,  4,  8,  1,  1,  9,  7,  7,
       10,  2,  2,  7,  6, 11,  1,  6, 10, 11,  5,  9,  9,  5,  2,  7,  0,
        1, 10,  5, 11,  8,  3,  0, 12,  8,  2,  9,  4, 11, 10,  6,  4])

In [1]:
import numpy as np 
a = np.random.randint(0,9,(2,4,4))
b = np.random.randint(0,9,(2,4,4))
#a
#b
# a-b 
# c = (a-b)[:,:3,3]
# c
# np.linalg.norm(c,axis=1)

a_rot = a[:,:3,:3]
b_rot = b[:,:3,:3]
a_rot_T = np.transpose(a_rot,axes=[0,2,1])

diff_matrix = np.matmul(b_rot,a_rot_T)
v = (np.trace(diff_matrix,axis1=1,axis2=2)-1)/2
v




theta = np.arccos(np.clip(v, -1, 1))







In [62]:
np.arccos([0.95,0.18])

np.arccos(0.95)


array([0.31756043, 1.38980988])

0.3175604292915215

In [120]:
b = np.random.random((4,4))
t_matrix = np.eye(4)   
t_vec = np.array([0.0, 0.0, np.round(perc_error_dome * smaller_dome_radius * np.random.uniform(-1.0,1.0),4)])
t_matrix[:3,3] = t_vec

b
t_matrix


array([[0.83656227, 0.04084508, 0.37339588, 0.78596507],
       [0.37147238, 0.60388013, 0.6750007 , 0.70943548],
       [0.5141296 , 0.97373059, 0.41478927, 0.95299612],
       [0.3424068 , 0.14984989, 0.28326254, 0.60507789]])

array([[ 1.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  1.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  1.   , -0.011],
       [ 0.   ,  0.   ,  0.   ,  1.   ]])

In [171]:

b @ t_matrix

array([[0.83656227, 0.04084508, 0.37339588, 0.78185771],
       [0.37147238, 0.60388013, 0.6750007 , 0.70201047],
       [0.5141296 , 0.97373059, 0.41478927, 0.94843343],
       [0.3424068 , 0.14984989, 0.28326254, 0.601962  ]])

In [3]:

from os import listdir
from os.path import isfile
from pathlib import Path

def load_images(path: str) -> list:
    
    img_files = [f for f in listdir(path) if f.endswith(".JPG")]
    for idx,file in enumerate(img_files):
        file = path / file
        file.rename(file.parent / (str(idx).zfill(5) + '_image' + file.suffix.lower()))        


path = Path('/home/eyecan/dev/real_relight/data/datasets/train/cubesOnShelf_multiLight/from_uf/camera/lset1/data')

a = load_images(path)

a


In [2]:
import cv2
import os
from pathlib import Path 

images_path = Path('/home/eyecan/dev/real_relight/data/datasets/train/cubesOnShelf_fixedLight/uf/data')

width = 696
height = 464
dim = (width, height)

def load_images(path: str) -> list:

    files = [f for f in listdir(path) if f.endswith(".jpeg")]
    files = sorted(files)

    return files


images = load_images(images_path)

for img_name in images : 

    img_path = str(images_path / img_name)

    img = cv2.imread(img_path, cv2.IMREAD_UNCHANGED)
    resized = cv2.resize(img, dim, interpolation = cv2.INTER_AREA)

    os.remove(img_path)

    cv2.imwrite(img_path, resized)
 
print('Resized Dimensions : ',resized.shape)
 

Resized Dimensions :  (464, 696, 3)


In [15]:
4315.606657494824 / 4
1251.4190878790973 / 4
4366.2957062460355 / 4
949.0947809821362 / 4

1078.901664373706

312.85477196977433

1091.5739265615089

237.27369524553404

In [8]:
import yaml 
import numpy as np 


camera_metadata = {
        "camera_pose": {
            "rotation": np.eye(3).tolist(),
            "translation": np.zeros(3).tolist(),
        },
        "intrinsics": {
            "camera_matrix": [1,2,3],
            "dist_coeffs": [4,5,6],
            "image_size": [30,50],
        },
    }


path = Path('/home/eyecan/dev/real_relight/data/datasets/train/prove/prova0/calibration')

with open(path / 'camera.yml', "w") as f : 
    yaml.dump(camera_metadata, f)



In [11]:
import cv2 
from cv2 import aruco 

n_markers = 18
marker_res = 5
grid_size = [6,6]
square_size_meters = 0.03
marker_size_meters = 0.018

dictionary = aruco.Dictionary_create(n_markers, marker_res)
board = aruco.CharucoBoard_create(grid_size[1], grid_size[0], square_size_meters, marker_size_meters, dictionary)

input_image = cv2.cvtColor(board.draw((500, 500)), cv2.COLOR_GRAY2BGR)
cv2.imwrite("/home/eyecan/dev/real_relight/data/datasets/train/prove/prova0/calibration/base", cv2.cvtColor(input_image, cv2.COLOR_BGR2RGB))

ImportError: cannot import name 'aruco' from 'cv2' (/home/eyecan/dev/venv/ngp/lib/python3.8/site-packages/cv2/__init__.py)

In [1]:
import shutil

shutil.copy('/home/eyecan/dev/real_relight/data/datasets/train/cubesOnShelf_multiLight/config/prova.txt', '/home/eyecan/dev/real_relight/data/datasets/train/cubesOnShelf_multiLight/prova/ciao.txt')     

'/home/eyecan/dev/real_relight/data/datasets/train/cubesOnShelf_multiLight/prova/ciao.txt'