In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

%load_ext autoreload
%autoreload 2

In [26]:
import numpy as np 

t_matrix = np.eye(4)
t_matrix[0, 3] = 2

rt = np.random.randint(0,9,(4,4))

t_matrix

rt[3,:-1] = 0
rt[3,-1] = 1

rt

rt @ t_matrix
np.linalg.inv(np.linalg.inv(t_matrix) @ np.linalg.inv(rt))

array([[1., 0., 0., 2.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

array([[7, 4, 2, 6],
       [1, 7, 7, 1],
       [5, 1, 0, 5],
       [0, 0, 0, 1]])

array([[ 7.,  4.,  2., 20.],
       [ 1.,  7.,  7.,  3.],
       [ 5.,  1.,  0., 15.],
       [ 0.,  0.,  0.,  1.]])

array([[ 7.,  4.,  2., 20.],
       [ 1.,  7.,  7.,  3.],
       [ 5.,  1.,  0., 15.],
       [ 0.,  0.,  0.,  1.]])

In [33]:
cam2world_matrix =  np.random.randint(0,9,(4,4))
cam2world_matrix[3,:-1] = 0
cam2world_matrix[3,-1] = 1

t_vec = np.array([2,0,0])
t_matrix = np.eye(4)
t_matrix[:3,3] = t_vec



c2l = cam2world_matrix @ t_matrix
light_location = c2l[:3,3]

cam2world_matrix
t_matrix
c2l
light_location

array([[1, 4, 3, 6],
       [2, 2, 6, 5],
       [8, 8, 1, 5],
       [0, 0, 0, 1]])

array([[1., 0., 0., 2.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

array([[ 1.,  4.,  3.,  8.],
       [ 2.,  2.,  6.,  9.],
       [ 8.,  8.,  1., 21.],
       [ 0.,  0.,  0.,  1.]])

array([ 8.,  9., 21.])

In [5]:
from pathlib import Path

BASE_PATH = Path('~/dev').expanduser()
DATASET_PATH = BASE_PATH/'data'/'dataset'
SCENE_PATH =  BASE_PATH/'data'/'scenes'
CONFIG_FOLDER = BASE_PATH/'data'/'dataset'/'config'


BASE_PATH
CONFIG_FOLDER

PosixPath('/home/eyecan/dev/data/dataset/config')

In [1]:
import json
data = {1 : 'ciao'}
with open('data.json', 'w') as f:
    json.dump(data, f)