In [25]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

%load_ext autoreload
%autoreload 2

In [26]:
import numpy as np 

t_matrix = np.eye(4)
t_matrix[0, 3] = 2

rt = np.random.randint(0,9,(4,4))

t_matrix

rt[3,:-1] = 0
rt[3,-1] = 1

rt

rt @ t_matrix
np.linalg.inv(np.linalg.inv(t_matrix) @ np.linalg.inv(rt))

array([[1., 0., 0., 2.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

array([[7, 4, 2, 6],
       [1, 7, 7, 1],
       [5, 1, 0, 5],
       [0, 0, 0, 1]])

array([[ 7.,  4.,  2., 20.],
       [ 1.,  7.,  7.,  3.],
       [ 5.,  1.,  0., 15.],
       [ 0.,  0.,  0.,  1.]])

array([[ 7.,  4.,  2., 20.],
       [ 1.,  7.,  7.,  3.],
       [ 5.,  1.,  0., 15.],
       [ 0.,  0.,  0.,  1.]])

In [33]:
cam2world_matrix =  np.random.randint(0,9,(4,4))
cam2world_matrix[3,:-1] = 0
cam2world_matrix[3,-1] = 1

t_vec = np.array([2,0,0])
t_matrix = np.eye(4)
t_matrix[:3,3] = t_vec



c2l = cam2world_matrix @ t_matrix
light_location = c2l[:3,3]

cam2world_matrix
t_matrix
c2l
light_location

array([[1, 4, 3, 6],
       [2, 2, 6, 5],
       [8, 8, 1, 5],
       [0, 0, 0, 1]])

array([[1., 0., 0., 2.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

array([[ 1.,  4.,  3.,  8.],
       [ 2.,  2.,  6.,  9.],
       [ 8.,  8.,  1., 21.],
       [ 0.,  0.,  0.,  1.]])

array([ 8.,  9., 21.])

In [5]:
from pathlib import Path

BASE_PATH = Path('~/dev').expanduser()
DATASET_PATH = BASE_PATH/'data'/'dataset'
SCENE_PATH =  BASE_PATH/'data'/'scenes'
CONFIG_FOLDER = BASE_PATH/'data'/'dataset'/'config'


BASE_PATH
CONFIG_FOLDER

PosixPath('/home/eyecan/dev/data/dataset/config')

In [1]:
import json
data = {1 : 'ciao'}
with open('data.json', 'w') as f:
    json.dump(data, f)

In [2]:
import numpy as np
def n_points_on_circle(r, center, num_points):
    theta = np.linspace(0,2*np.pi,num_points,endpoint=False); 
    x = r * np.cos(theta)+center[0]
    y = r * np.sin(theta)+center[1]
    z = np.broadcast_to(center[2],num_points)

    print(x)
    print(y)
    print(z)

    xyz = np.stack((x,y,z),axis=-1)
    return xyz


n_points_on_circle(0.6,[0,0,0],10)

[ 0.6        0.4854102  0.1854102 -0.1854102 -0.4854102 -0.6
 -0.4854102 -0.1854102  0.1854102  0.4854102]
[ 0.00000000e+00  3.52671151e-01  5.70633910e-01  5.70633910e-01
  3.52671151e-01  7.34788079e-17 -3.52671151e-01 -5.70633910e-01
 -5.70633910e-01 -3.52671151e-01]
[0 0 0 0 0 0 0 0 0 0]


array([[ 6.00000000e-01,  0.00000000e+00,  0.00000000e+00],
       [ 4.85410197e-01,  3.52671151e-01,  0.00000000e+00],
       [ 1.85410197e-01,  5.70633910e-01,  0.00000000e+00],
       [-1.85410197e-01,  5.70633910e-01,  0.00000000e+00],
       [-4.85410197e-01,  3.52671151e-01,  0.00000000e+00],
       [-6.00000000e-01,  7.34788079e-17,  0.00000000e+00],
       [-4.85410197e-01, -3.52671151e-01,  0.00000000e+00],
       [-1.85410197e-01, -5.70633910e-01,  0.00000000e+00],
       [ 1.85410197e-01, -5.70633910e-01,  0.00000000e+00],
       [ 4.85410197e-01, -3.52671151e-01,  0.00000000e+00]])

In [2]:
import shutil

shutil.move('/home/eyecan/Downloads/prova/render/','/home/eyecan/dev/data/blender/light360_2')

'/home/eyecan/dev/data/blender/light360_2/render'

In [3]:
import shutil 
shutil.rmtree('/home/eyecan/dev/data/blender_tmp/truck_HD')

In [5]:
import shutil
from pathlib import Path 
p = Path('/home/eyecan/dev/data/blender_tmp/truck_HD_light_360/bbox.npy')
shutil.copy(p,'/home/eyecan/dev/data/blender_tmp/prova_copy')

'/home/eyecan/dev/data/blender_tmp/prova_copy/bbox.npy'

In [8]:
BASE_PATH = Path('~/dev').expanduser()      #TOCHANGE cosi è specifico per questo pc 
DATASET_PATH = BASE_PATH/'data'/'dataset'
BLENDER_PATH = BASE_PATH/'data'/'blender_tmp'

in_blender_tmp_folder = BLENDER_PATH / id
out_underfolder_path = DATASET_PATH / 'train' / id
render_path = in_blender_tmp_folder / 'render'

shutil.move(str(render_path), str(out_underfolder_path))   #DEBUG 
shutil.rmtree(in_blender_tmp_folder) #DEBUG 

In [ ]:
import numpy as np 

n= 50
a = np.arange(0,n)
b = a.copy()
np.random.shuffle(b)




In [37]:
a = np.random.randint(0,9,(10,4))
a
np.random.shuffle(a)
a

array([[2, 1, 5, 3],
       [7, 0, 2, 7],
       [2, 0, 3, 8],
       [5, 7, 6, 5],
       [0, 7, 7, 0],
       [6, 7, 3, 8],
       [1, 1, 2, 6],
       [7, 6, 5, 1],
       [6, 8, 1, 8],
       [0, 6, 6, 3]])

array([[7, 0, 2, 7],
       [0, 6, 6, 3],
       [2, 1, 5, 3],
       [6, 8, 1, 8],
       [1, 1, 2, 6],
       [7, 6, 5, 1],
       [0, 7, 7, 0],
       [2, 0, 3, 8],
       [5, 7, 6, 5],
       [6, 7, 3, 8]])

In [40]:
#FOR GENERATING UNIQUE IDS 

import itertools
import string
import os 
import yaml


BASE_PATH = Path('~/dev').expanduser()      #TOCHANGE cosi è specifico per questo pc 
DATASET_PATH = BASE_PATH/'data'/'dataset'

valid_chars = set(string.ascii_lowercase + string.digits)

unique_id_generator = itertools.combinations(valid_chars, 5)

id_file = os.path.join(DATASET_PATH,'id.yml')

with open(id_file,"r") as f :
    id_dict = yaml.load(f, Loader=yaml.FullLoader)

print(id_dict)

for gen_id in unique_id_generator:
    _id = "".join(gen_id)
    if _id not in id_dict :
        id = _id

print(id)



{'light360': 'the light goes in a circle around the object while the camera is fixed'}
v4yx2
