In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

%load_ext autoreload
%autoreload 2

In [3]:
import numpy as np 

t_matrix = np.eye(4)
t_matrix[0, 3] = 2

rt = np.random.randint(0,9,(4,4))

t_matrix

rt[3,:-1] = 0
rt[3,-1] = 1

rt

rt @ t_matrix
np.linalg.inv(np.linalg.inv(t_matrix) @ np.linalg.inv(rt))

array([[1., 0., 0., 2.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

array([[5, 7, 1, 3],
       [7, 6, 4, 6],
       [7, 0, 6, 1],
       [0, 0, 0, 1]])

array([[ 5.,  7.,  1., 13.],
       [ 7.,  6.,  4., 20.],
       [ 7.,  0.,  6., 15.],
       [ 0.,  0.,  0.,  1.]])

array([[5.00000000e+00, 7.00000000e+00, 1.00000000e+00, 1.30000000e+01],
       [7.00000000e+00, 6.00000000e+00, 4.00000000e+00, 2.00000000e+01],
       [7.00000000e+00, 9.49240686e-15, 6.00000000e+00, 1.50000000e+01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [ ]:
cam2world_matrix =  np.random.randint(0,9,(4,4))
cam2world_matrix[3,:-1] = 0
cam2world_matrix[3,-1] = 1

t_vec = np.array([2,0,0])
t_matrix = np.eye(4)
t_matrix[:3,3] = t_vec



c2l = cam2world_matrix @ t_matrix
light_location = c2l[:3,3]

cam2world_matrix
t_matrix
c2l
light_location

In [ ]:
from pathlib import Path

BASE_PATH = Path('~/dev').expanduser()
DATASET_PATH = BASE_PATH/'data'/'dataset'
SCENE_PATH =  BASE_PATH/'data'/'scenes'
CONFIG_FOLDER = BASE_PATH/'data'/'dataset'/'config'


BASE_PATH
CONFIG_FOLDER

In [ ]:
import json
data = {1 : 'ciao'}
with open('data.json', 'w') as f:
    json.dump(data, f)

In [ ]:
import numpy as np
def n_points_on_circle(r, center, num_points):
    theta = np.linspace(0,2*np.pi,num_points,endpoint=False); 
    x = r * np.cos(theta)+center[0]
    y = r * np.sin(theta)+center[1]
    z = np.broadcast_to(center[2],num_points)

    print(x)
    print(y)
    print(z)

    xyz = np.stack((x,y,z),axis=-1)
    return xyz


n_points_on_circle(0.6,[0,0,0],10)

In [ ]:
import shutil

shutil.move('/home/eyecan/Downloads/prova/render/','/home/eyecan/dev/data/blender/light360_2')

In [ ]:
import shutil 
shutil.rmtree('/home/eyecan/dev/data/blender_tmp/truck_HD')

In [ ]:
import shutil
from pathlib import Path 
p = Path('/home/eyecan/dev/data/blender_tmp/truck_HD_light_360/bbox.npy')
shutil.copy(p,'/home/eyecan/dev/data/blender_tmp/prova_copy')

In [ ]:
BASE_PATH = Path('~/dev').expanduser()      #TOCHANGE cosi è specifico per questo pc 
DATASET_PATH = BASE_PATH/'data'/'dataset'
BLENDER_PATH = BASE_PATH/'data'/'blender_tmp'

in_blender_tmp_folder = BLENDER_PATH / id
out_underfolder_path = DATASET_PATH / 'train' / id
render_path = in_blender_tmp_folder / 'render'

shutil.move(str(render_path), str(out_underfolder_path))   #DEBUG 
shutil.rmtree(in_blender_tmp_folder) #DEBUG 

In [ ]:
import numpy as np 

n= 50
a = np.arange(0,n)
b = a.copy()
np.random.shuffle(b)




In [ ]:
a = np.random.randint(0,9,(10,4))
a
np.random.shuffle(a)
a

In [ ]:
#FOR GENERATING UNIQUE IDS 

import itertools
import string
import os 
import yaml


BASE_PATH = Path('~/dev').expanduser()      #TOCHANGE cosi è specifico per questo pc 
DATASET_PATH = BASE_PATH/'data'/'dataset'

valid_chars = set(string.ascii_lowercase + string.digits)

unique_id_generator = itertools.combinations(valid_chars, 5)

id_file = os.path.join(DATASET_PATH,'id.yml')

with open(id_file,"r") as f :
    id_dict = yaml.load(f, Loader=yaml.FullLoader)

print(id_dict)

for gen_id in unique_id_generator:
    _id = "".join(gen_id)
    if _id not in id_dict :
        id = _id

print(id)



In [ ]:
import numpy as np 

tv_list = [[2,0,0],[0,0,2],[-2,0,0],[0,0,-2]]
t_vecs = np.array(tv_list)   #convert the t_vector in numpy array  
t_matrices = np.zeros((t_vecs.shape[0],4,4))

#generate translation matrices from translation vector list
for i, t_vec in enumerate(t_vecs) :
    t_matrices[i] = np.eye(4)                                        
    t_matrices[i,:3,3] = t_vec

t_matrices


In [ ]:
import numpy as np 
c_idxs = np.arange(0,20)
l_idxs = c_idxs.copy()
c_idxs
l_idxs

np.random.shuffle(c_idxs)  
np.random.shuffle(l_idxs)

print([(c_id,l_id) for c_id, l_id in zip(c_idxs,l_idxs)])
   

In [ ]:
import numpy as np 
r = 2.0

c = np.round(0.2 * r * np.random.uniform(-1.0,1.0),4)

c



In [ ]:
import numpy as np 
a = np.random.randint(0,9,(2,4,4))
b = np.random.randint(0,9,(2,4,4))
#a
#b
# a-b 
# c = (a-b)[:,:3,3]
# c
# np.linalg.norm(c,axis=1)

a_rot = a[:,:3,:3]
b_rot = b[:,:3,:3]
a_rot_T = np.transpose(a_rot,axes=[0,2,1])

diff_matrix = np.matmul(b_rot,a_rot_T)
v = (np.trace(diff_matrix,axis1=1,axis2=2)-1)/2
v




theta = np.arccos(np.clip(v, -1, 1))







In [ ]:
np.arccos([0.95,0.18])

np.arccos(0.95)


In [8]:
import numpy as np 
import math 

num_poses = 8
num_repeated_lights = 3

c_idxs = np.arange(0,num_poses)
l_idxs = np.arange(0,math.ceil(num_poses / num_repeated_lights))
l_idxs
l_idxs = np.repeat(l_idxs,num_repeated_lights)[:num_poses]

c_idxs 
l_idxs

np.random.shuffle(c_idxs)
np.random.shuffle(l_idxs)

c_idxs 
l_idxs

array([0, 1, 2])

array([0, 1, 2, 3, 4, 5, 6, 7])

array([0, 0, 0, 1, 1, 1, 2, 2])

array([7, 3, 4, 2, 0, 5, 6, 1])

array([1, 0, 0, 1, 2, 1, 2, 0])

In [15]:
import numpy as np 
import math 

num_poses = 10
num_lights = 4

c_idxs = np.arange(0,num_poses)
l_idxs = np.arange(0,num_lights)
l_idxs = np.tile(l_idxs,reps=3)[:num_poses] #np.repeat(l_idxs,num_repeated_lights)[:num_poses]
#l_idxs_b = np.repeat(l_idxs,num_repeated_lights)[:num_poses]


c_idxs 
l_idxs
#l_idxs_b

np.random.shuffle(c_idxs)
np.random.shuffle(l_idxs)

c_idxs 
l_idxs

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1])

array([8, 9, 2, 4, 5, 3, 1, 7, 0, 6])

array([0, 0, 1, 3, 2, 0, 1, 2, 1, 3])

In [ ]:
a = np.random.randint(0,9,(4,4))
b = np.random.randint(0,9,(4,4))


a

b

np.unique([a,b,a],axis=0)

In [8]:

l_idxs = np.repeat([1,2,3],1)[:6]

l_idxs


array([1, 2, 3])

In [9]:
input_start = 0.0
input_end = 1.0
output_start = 0.3
output_end = 0.7


input = 0.2


output = output_start + (output_end - output_start) * input 

output 

0.38

In [19]:
poses = np.random.randint(0,9,(3,4,4))
camera_id = 2
camera_poses = np.repeat(poses[camera_id,None,:], 3, axis=0)


poses
camera_poses


len(camera_poses)
camera_poses[1].shape

array([[[5, 3, 0, 3],
        [0, 6, 0, 1],
        [6, 3, 0, 0],
        [8, 1, 0, 5]],

       [[0, 0, 0, 2],
        [3, 5, 0, 2],
        [7, 5, 1, 6],
        [4, 7, 1, 5]],

       [[5, 1, 2, 3],
        [8, 0, 6, 4],
        [0, 3, 7, 7],
        [2, 3, 6, 6]]])

array([[[5, 1, 2, 3],
        [8, 0, 6, 4],
        [0, 3, 7, 7],
        [2, 3, 6, 6]],

       [[5, 1, 2, 3],
        [8, 0, 6, 4],
        [0, 3, 7, 7],
        [2, 3, 6, 6]],

       [[5, 1, 2, 3],
        [8, 0, 6, 4],
        [0, 3, 7, 7],
        [2, 3, 6, 6]]])

3

(4, 4)